apiVersion: apps/v1
kind: Deployment
metadata:
  name: ncjwhvq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ncjwhvq
  template:
    metadata:
      labels:
        app: ncjwhvq
    spec:
      containers:
      - image: okteto.dev/ncjwhvq:latest
        name: ncjwhvq
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "0073f47d-e336-4c18-8b7f-0b4ba3776203"
        - name: Vless_Path
          value: "/vless"
        - name: Vmess_UUID
          value: "0073f47d-e336-4c18-8b7f-0b4ba3776203"
        - name: Vmess_Path
          value: "/vmess"
        - name: Share_Path
          value: "/v2link"
